site_name: "SemiBin"
repo_url: "https://github.com/BigDataBiology/SemiBin"

nav:
        - 'SemiBin': index.md
        - 'Install': install.md
        - 'Usage': usage.md
        - 'Generating inputs to SemiBin': generate.md
        - 'Output' : output.md
        - "What's New": whatsnew.md

