name: s3n2bin_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pandas
        pip install numpy
        pip install .
        pip install pytest
        pip install atomicwrites
    - name: Test with pytest
      run: |
        python -m pytest ./test/test_cov.py
        python -m pytest ./test/test_kmer.py