name: semibin_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        environment:
          - "test-py38"
          - "test-py39"
          - "test-py310"
          - "test-py311"
          - "test-py312"
          - "test-py313"
    steps:
    - name: Checking out code
      uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.8.2
      with:
        pixi-version: v0.41.3
        activate-environment: true
        environments: ${{ matrix.environment }}
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest
    - name: Install into the environment
      shell: bash -l {0}
      run: |
        uv pip install .
    - name: Test with SemiBin command
      run: |
        uv pip install .
        for t in integration-tests/*.py; do
          echo "Running $t ..."
          python $t
        done

